# Generated by Django 5.1.6 on 2025-03-18 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('social_media', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section1_banner', models.ImageField(blank=True, null=True, upload_to='contact_page/section1/banner')),
                ('section1_title', models.CharField(blank=True, max_length=255, null=True)),
                ('section1_description', models.CharField(blank=True, max_length=255, null=True)),
                ('section2_banner', models.ImageField(blank=True, null=True, upload_to='contact_page/section2/banner')),
                ('section2_title', models.CharField(blank=True, max_length=255, null=True)),
                ('section1_social_media', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='social_media.socialmedia')),
            ],
        ),
    ]
