# Generated by Django 5.1.6 on 2025-03-30 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_page', '0003_rename_section1_description_contactpage_section1_form_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactpage',
            name='section1_form_title',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='section1_form_title_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='section1_form_title_es',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='section1_form_title_pt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='section2_banner_title',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='section2_banner_title_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='section2_banner_title_es',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='section2_banner_title_pt',
            field=models.TextField(blank=True, null=True),
        ),
    ]
