# Generated by Django 5.1.6 on 2025-03-30 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frequently_questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='frequentlyquestions',
            name='answer_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='frequentlyquestions',
            name='answer_es',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='frequentlyquestions',
            name='answer_pt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='frequentlyquestions',
            name='question_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='frequentlyquestions',
            name='question_es',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='frequentlyquestions',
            name='question_pt',
            field=models.TextField(blank=True, null=True),
        ),
    ]
