# Generated by Django 5.1.4 on 2025-02-18 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('our_services', '0002_alter_ourservice_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ourservice',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='ourServices/'),
        ),
    ]
