# Generated by Django 5.1.6 on 2025-03-26 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('our_services', '0003_alter_ourservice_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='ourservice',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ourservice',
            name='description_es',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ourservice',
            name='description_pt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ourservice',
            name='subtitle_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ourservice',
            name='subtitle_es',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ourservice',
            name='subtitle_pt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ourservice',
            name='title_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ourservice',
            name='title_es',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ourservice',
            name='title_pt',
            field=models.TextField(blank=True, null=True),
        ),
    ]
