# Generated by Django 5.1.6 on 2025-03-28 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('our_services', '0005_alter_ourservice_subtitle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ourservice',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='our_services/'),
        ),
    ]
