# Generated by Django 5.1.6 on 2025-03-23 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0004_blog_category_en_blog_category_es_blog_category_pt_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_page', models.ManyToManyField(related_name='blog_pages', to='blog.blog')),
            ],
        ),
    ]
