# Generated by Django 5.1.4 on 2025-02-17 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='user_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/userImage/'),
        ),
    ]
