# Generated by Django 5.1.4 on 2025-02-18 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_alter_feedback_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='user_image',
            field=models.ImageField(blank=True, null=True, upload_to='userImage/'),
        ),
    ]
