# Generated by Django 5.1.6 on 2025-03-28 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_alter_feedback_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='user_image',
            field=models.ImageField(blank=True, null=True, upload_to='feedback/user_image'),
        ),
    ]
