# Generated by Django 5.1.6 on 2025-03-29 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0004_alter_feedback_user_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='occupation',
            new_name='role',
        ),
    ]
