# Generated by Django 5.1.6 on 2025-03-26 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('our_services', '0004_ourservice_description_en_ourservice_description_es_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurServicesPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section1_title', models.CharField(blank=True, max_length=255, null=True)),
                ('section1_title_en', models.CharField(blank=True, max_length=255, null=True)),
                ('section1_title_pt', models.CharField(blank=True, max_length=255, null=True)),
                ('section1_title_es', models.CharField(blank=True, max_length=255, null=True)),
                ('section1_subtitle', models.CharField(blank=True, max_length=255, null=True)),
                ('section1_subtitle_en', models.CharField(blank=True, max_length=255, null=True)),
                ('section1_subtitle_pt', models.CharField(blank=True, max_length=255, null=True)),
                ('section1_subtitle_es', models.CharField(blank=True, max_length=255, null=True)),
                ('section1_image', models.ImageField(blank=True, null=True, upload_to='our_service_page/section1/image')),
                ('section3_title', models.CharField(blank=True, max_length=255, null=True)),
                ('section3_title_en', models.CharField(blank=True, max_length=255, null=True)),
                ('section3_title_pt', models.CharField(blank=True, max_length=255, null=True)),
                ('section3_title_es', models.CharField(blank=True, max_length=255, null=True)),
                ('section3_banner', models.ImageField(blank=True, null=True, upload_to='our_service_page/section3/banner')),
                ('section2_services', models.ManyToManyField(blank=True, null=True, related_name='our_services_pages', to='our_services.ourservice')),
            ],
        ),
    ]
