# Generated by Django 5.1.6 on 2025-03-28 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0005_vehicle_car_amenities_en_vehicle_car_amenities_es_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurFleetPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section1_title', models.CharField(blank=True, max_length=255, null=True)),
                ('section1_title_en', models.CharField(blank=True, max_length=255, null=True)),
                ('section1_title_pt', models.CharField(blank=True, max_length=255, null=True)),
                ('section1_title_es', models.CharField(blank=True, max_length=255, null=True)),
                ('section1_subtitle', models.CharField(blank=True, max_length=255, null=True)),
                ('section1_subtitle_en', models.CharField(blank=True, max_length=255, null=True)),
                ('section1_subtitle_pt', models.CharField(blank=True, max_length=255, null=True)),
                ('section1_subtitle_es', models.CharField(blank=True, max_length=255, null=True)),
                ('section1_banner', models.ImageField(blank=True, null=True, upload_to='our_fleet_page/section1/banner')),
                ('section2_vehicles', models.ManyToManyField(blank=True, null=True, related_name='our_fleet_pages', to='vehicles.vehicle')),
            ],
        ),
    ]
