# Generated by Django 5.1.6 on 2025-03-27 21:21

import social_media.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_media', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialmedia',
            name='email',
        ),
        migrations.RemoveField(
            model_name='socialmedia',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='socialmedia',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='socialmedia',
            name='phone_whatsapp1',
        ),
        migrations.RemoveField(
            model_name='socialmedia',
            name='phone_whatsapp2',
        ),
        migrations.RemoveField(
            model_name='socialmedia',
            name='x',
        ),
        migrations.AddField(
            model_name='socialmedia',
            name='icon',
            field=models.FileField(blank=True, null=True, upload_to='social_media/icons/', validators=[social_media.models.validate_svg]),
        ),
        migrations.AddField(
            model_name='socialmedia',
            name='label',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='socialmedia',
            name='label_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='socialmedia',
            name='label_es',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='socialmedia',
            name='label_pt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='socialmedia',
            name='value',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
