# Generated by Django 5.1.6 on 2025-03-20 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BeAPartnerPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section1_banner', models.ImageField(blank=True, null=True, upload_to='be_a_partner_page/section1/banner')),
                ('section1_banner_title', models.CharField(blank=True, max_length=255, null=True)),
                ('section1_banner_title_en', models.CharField(blank=True, max_length=255, null=True)),
                ('section1_banner_title_pt', models.CharField(blank=True, max_length=255, null=True)),
                ('section1_banner_title_es', models.CharField(blank=True, max_length=255, null=True)),
                ('section1_banner_description', models.CharField(blank=True, max_length=255, null=True)),
                ('section1_banner_description_en', models.CharField(blank=True, max_length=255, null=True)),
                ('section1_banner_description_pt', models.CharField(blank=True, max_length=255, null=True)),
                ('section1_banner_description_es', models.CharField(blank=True, max_length=255, null=True)),
                ('section1_form_title', models.CharField(blank=True, max_length=255, null=True)),
                ('section1_form_title_en', models.CharField(blank=True, max_length=255, null=True)),
                ('section1_form_title_pt', models.CharField(blank=True, max_length=255, null=True)),
                ('section1_form_title_es', models.CharField(blank=True, max_length=255, null=True)),
                ('section1_form_description', models.CharField(blank=True, max_length=255, null=True)),
                ('section1_form_description_en', models.CharField(blank=True, max_length=255, null=True)),
                ('section1_form_description_pt', models.CharField(blank=True, max_length=255, null=True)),
                ('section1_form_description_es', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
