# Generated by Django 5.1.6 on 2025-03-28 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('be_a_partner_page', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beapartnerpage',
            name='section1_banner_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='beapartnerpage',
            name='section1_banner_description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='beapartnerpage',
            name='section1_banner_description_es',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='beapartnerpage',
            name='section1_banner_description_pt',
            field=models.TextField(blank=True, null=True),
        ),
    ]
