# Generated by Django 5.1.6 on 2025-03-30 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('be_a_partner_page', '0002_alter_beapartnerpage_section1_banner_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beapartnerpage',
            name='section1_banner_title',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='beapartnerpage',
            name='section1_banner_title_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='beapartnerpage',
            name='section1_banner_title_es',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='beapartnerpage',
            name='section1_banner_title_pt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='beapartnerpage',
            name='section1_form_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='beapartnerpage',
            name='section1_form_description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='beapartnerpage',
            name='section1_form_description_es',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='beapartnerpage',
            name='section1_form_description_pt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='beapartnerpage',
            name='section1_form_title',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='beapartnerpage',
            name='section1_form_title_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='beapartnerpage',
            name='section1_form_title_es',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='beapartnerpage',
            name='section1_form_title_pt',
            field=models.TextField(blank=True, null=True),
        ),
    ]
