# Generated by Django 5.1.4 on 2025-02-10 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(blank=True, max_length=255, null=True)),
                ('car_type', models.CharField(blank=True, max_length=255, null=True)),
                ('quantity_seats', models.IntegerField(blank=True, null=True)),
                ('quantity_luggage', models.IntegerField(blank=True, null=True)),
                ('car_image', models.ImageField(blank=True, null=True, upload_to='vehicles/')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('car_overview', models.TextField(blank=True, null=True)),
                ('car_amenities', models.TextField(blank=True, null=True)),
                ('car_best_for_services', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
