# Generated by Django 5.1.4 on 2025-02-18 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_alter_vehicle_car_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='car_image',
            field=models.ImageField(blank=True, null=True, upload_to='vehicles/'),
        ),
    ]
