# Generated by Django 5.1.6 on 2025-02-25 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0003_alter_vehicle_car_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='price',
            new_name='price_hour',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='price_km',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
