# Generated by Django 5.1.6 on 2025-03-30 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='section2_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='section2_description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='section2_description_es',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='section2_description_pt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='section1_title',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='section1_title_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='section1_title_es',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='section1_title_pt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='section2_title',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='section2_title_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='section2_title_es',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='section2_title_pt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='section4_title',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='section4_title_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='section4_title_es',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='section4_title_pt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='section5_title',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='section5_title_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='section5_title_es',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='section5_title_pt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='section6_title',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='section6_title_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='section6_title_es',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='section6_title_pt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='section7_title',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='section7_title_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='section7_title_es',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='section7_title_pt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='section8_title',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='section8_title_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='section8_title_es',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='section8_title_pt',
            field=models.TextField(blank=True, null=True),
        ),
    ]
