# Generated by Django 5.1.6 on 2025-02-27 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0004_rename_price_vehicle_price_hour_vehicle_price_km'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_route', models.CharField(blank=True, max_length=255, null=True)),
                ('to_route', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('hour', models.TimeField(blank=True, null=True)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('estimated_time', models.TimeField(blank=True, null=True)),
                ('distance_km', models.FloatField(blank=True, null=True)),
                ('booking_for', models.CharField(blank=True, choices=[('myself', 'Book for Myself'), ('someone_else', 'Book for Someone else')], max_length=20, null=True)),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(blank=True, choices=[('Mr', 'Mr'), ('Ms', 'Ms')], max_length=2, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=50, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('payment_intent_id', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_status', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_brand', models.CharField(blank=True, max_length=255, null=True)),
                ('booking_date', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehicles.vehicle')),
            ],
        ),
    ]
