# Generated by Django 5.1.6 on 2025-02-28 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
