# Generated by Django 5.1.6 on 2025-05-02 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_alter_booking_booking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('upcoming', 'Upcoming'), ('past', 'Past'), ('canceled', 'Canceled')], max_length=255, null=True),
        ),
    ]
